mirror_main:
    resource: "@MirrorMainBundle/Controller/"
    type:     annotation
    prefix:   /main


mirror_api:
    resource: "@MirrorApiBundle/Controller/"
    type:     annotation
    prefix:   /api

mirror_adm:
    resource: "@MirrorAdmBundle/Controller/"
    type:     annotation
    prefix:   /adm

mirror_index:
    pattern:  /
    defaults: { _controller: MirrorMainBundle:Index:index }
