Goods:
    type: entity
    table: goods
    indexes:
        sort:
            columns:
                - sort_id
        price:
            columns:
                - price
        name:
            columns:
                - name
    uniqueConstraints:
        goodsNumber:
            columns:
                - goods_number
                - status
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 商品名称
        sortId:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 商品分类
            column: sort_id
        price:
            type: decimal
            nullable: false
            precision: 11
            scale: 2
            options:
                comment: 商品价格
                default: '0.00'
        image:
            type: integer
            nullable: true
            options:
                unsigned: false
                comment: 商品图片
                default: 'NULL'
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
                default: 'NULL'
        buyNum:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 订购次数
                default: '0'
            column: buy_num
        attr:
            type: blob
            nullable: true
            length: 65535
            options:
                fixed: false
                comment: 专有属性
                default: 'NULL'
        goodsNumber:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 货号
            column: goods_number
        unit:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                comment: 单位
        standard:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                comment: 规格
        vender:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                comment: 厂家
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: '''0000-00-00 00:00:00'''
            column: update_time
    lifecycleCallbacks: {  }
