User:
    type: entity
    table: user
    indexes:
        role:
            columns:
                - role
        status:
            columns:
                - status
    uniqueConstraints:
        mobile:
            columns:
                - mobile
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        mobile:
            type: string
            nullable: true
            length: 11
            options:
                fixed: false
                default: 'NULL'
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        image:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: 'NULL'
        role:
            type: integer
            nullable: false
            options:
                unsigned: false
        online:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: current_timestamp()
            column: update_time
    lifecycleCallbacks: {  }
